use std::str::FromStr;

use crate::{api::connection::proto, error::ProtoError, util::uuid::generate_uuid};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

use super::{LicksIdentifier, LicksIdentifierError};

/// `AccountId` is the identifier that is linked to someone's account
/// and is used to identify them.
///
/// They are generated by the server during registration.
#[derive(Debug, PartialEq, Eq, Clone, Copy, Serialize, Deserialize, Hash)]
pub struct AccountId(Uuid);

impl TryFrom<&[u8]> for AccountId {
    type Error = LicksIdentifierError;

    fn try_from(value: &[u8]) -> Result<Self, Self::Error> {
        let uuid: Uuid = Uuid::from_slice(value).map_err(|_| LicksIdentifierError::InvalidInput)?;

        Ok(AccountId::from(uuid))
    }
}

impl FromStr for AccountId {
    type Err = LicksIdentifierError;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        let uuid = Uuid::from_str(s).map_err(|_| LicksIdentifierError::InvalidInput)?;

        Ok(Self(uuid))
    }
}

impl AsRef<[u8]> for AccountId {
    fn as_ref(&self) -> &[u8] {
        self.0.as_bytes()
    }
}

impl From<Uuid> for AccountId {
    fn from(value: Uuid) -> Self {
        AccountId(value)
    }
}

impl std::fmt::Display for AccountId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Account({})", self.0)
    }
}

impl From<AccountId> for proto::AccountId {
    fn from(value: AccountId) -> Self {
        Self {
            uuid: value.to_bytes().into(),
        }
    }
}

impl TryFrom<proto::AccountId> for AccountId {
    type Error = ProtoError;

    fn try_from(value: proto::AccountId) -> Result<Self, Self::Error> {
        Ok(Self(Uuid::from_slice(&value.uuid).map_err(|_| ProtoError)?))
    }
}

impl LicksIdentifier for AccountId {
    fn generate_id() -> Self {
        AccountId(generate_uuid())
    }

    fn as_uuid(&self) -> Uuid {
        self.0
    }

    fn to_bytes(&self) -> [u8; 16] {
        self.0.into_bytes()
    }

    fn none() -> Self {
        AccountId(uuid::Uuid::nil())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::str::FromStr;

    const TEST_UUID: &str = "8311e830-eeea-48ca-8fe3-5bcf09e11b57";

    #[test]
    fn create_display_account_identifier() {
        let account_id = AccountId::from_str(TEST_UUID).expect("UUID is correctly formatted");

        assert_eq!(
            "Account(8311e830-eeea-48ca-8fe3-5bcf09e11b57)",
            format!("{account_id}")
        );
    }
}
