[application]

name = "Licks!"
default_platform = "desktop"
out_dir = "dist"
asset_dir = "assets"

[web.app]

title = "Licks!"

[web.watcher]

reload_html = true
watch_path = ["src", "assets"]

[web.resource]

style = ["assets/main.css"]
script = []

[web.resource.dev]

script = []
